spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  notify:
    mail:
      enabled: false
  kafka:
    annotation-request-topic: annotation-request
    annotation-result-topic: annotation-result
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: kafka:9092
    consumer:
      group-id: core-annotator
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.annotator.core.infrastructure.kafka.AnnotatedResultDeserializer
      bootstrap-servers: kafka:9092
      group-instance-id: result-client #skips rebalancing - remove in prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pzsp2-db-1:5432/annotator_db
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
